### ISSUE TITLE
Wagtail: Mobile Version for structured Page is not working/nice

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#168] opened 2020-04-01 11:27 UTC
**URL:** https://hidden.civic-europe.eu/civic-europe/team/
**user:** * initiator*
**expected behaviour:** *There should be a little Pedding on the Left Side
![photo_2020-04-01_12-05-19](https://user-images.githubusercontent.com/52459078/78132150-8192a880-741c-11ea-9e47-d0620af8d19f.jpg)
![photo_2020-04-01_13-27-00](https://user-images.githubusercontent.com/52459078/78132153-822b3f00-741c-11ea-90cd-b1147c8ab5e3.jpg)

*
**behaviour:** *The padding on the left is to close*
**important screensize:** *mobile*
**device & browser:** *Firefox, Safari, Chrome*

**Comment by phillimorland** [comment] 2020-12-21 15:50
cannot reproduce so closing

**Closed by phillimorland** 2020-12-21 15:50 UTC
Labels: Type: Responsive
